---

- name: debug.yml
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Update/clean/full-upgrade
      apt:
        update_cache: yes
        cache_valid_time: 86400
        autoclean: yes
        autoremove: yes
        upgrade: full
      become: yes

    - name: Update system pacakages
      apt:
        name: "*"
        state: latest
      become: yes
