---
- name: debug.yml
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Update/clean/full-upgrade
      apt:
        update_cache: true
        cache_valid_time: 86400
        autoclean: true
        autoremove: true
        upgrade: full
      become: true

    - name: Update system pacakages
      apt:
        name: "*"
        state: latest
      become: true
