---
- name: Developer
  hosts: localhost
  tasks:
    - name: "{{ role_item }}"
      ansible.builtin.include_role:
        name: "{{ role_item }}"
      loop:
        - languages
      loop_control:
        loop_var: role_item
