---

- name: developer.yml
  hosts: localhost
  tasks:

    # - meta: end_play

    - include_role:
        name: "{{ role_item }}"
      loop:
       - asdf
       - languages
      loop_control:
        loop_var: role_item
