---

- name: developer.yml
  hosts: localhost
  tasks:

    # - meta: end_play

    - name: Load bash aliases
      copy:
        src: aliases.sh
        dest: "~/.startup.d/aliases.sh"
        mode: '0644'

    - name: Load ansible config
      copy:
        src: ansible.sh
        dest: "~/.startup.d/ansible.sh"
        mode: '0644'

    # Use this until https://github.com/dw/mitogen/pull/739 gets merged
    - name: Install mitogen
      pip:
        name: git+https://github.com/MetricMike/mitogen.git@master
        state: latest

    - include_role:
        name: languages
