---
- name: DiscordGSM
  hosts: localhost
  tasks:
    - name: 2. Clone the repository # noqa: latest
      ansible.builtin.git:
        repo: https://github.com/DiscordGSM/GameServerMonitor.git
        dest: /home/metricmike/projects/GameServerMonitor
        update: false

    - name: 3-5. Create virtualenv and install python dependencies
      ansible.builtin.pip:
        requirements: /home/metricmike/projects/GameServerMonitor/requirements.txt
        virtualenv: /home/metricmike/projects/GameServerMonitor/venv
        virtualenv_command: python -m venv

    - name: 8. Create a service
      ansible.builtin.copy:
        src: discordgsm.service
        dest: /etc/systemd/system/discordgsm.service
        owner: metricmike
        group: metricmike
        mode: u=rw,go=r
      become: true

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
      become: true

    - name: Enable service
      ansible.builtin.systemd:
        name: discordgsm.service
        enabled: true
      become: true

    - name: Restart service
      ansible.builtin.systemd:
        name: discordgsm.service
        state: restarted
      become: true
