---

- name: Silence login motd
  file:
    path: ~/.hushlogin
    state: touch

- name: Add bash configurations
  copy:
    src: "{{ item }}.sh"
    dest: "~/.startup.d/{{ item }}.sh"
    mode: u=rw-,g=r--,o=r--
  loop:
    - 00_locale
    - resetclock
    - gpg

- name: Add gpg configurations
  copy:
    src: "{{ item }}.conf"
    dest: "~/.gnupg/{{ item }}.conf"
    mode: u=rw-,g=r--,o=r--
  loop:
    - gpg
    - gpg-agent
