---
- name: Silence login motd
  file:
    path: ~/.hushlogin
    state: touch

- name: Add bash configurations
  copy:
    src: "{{ item }}.sh"
    dest: "~/.startup.d/{{ item }}.sh"
    mode: u=rw-,g=r--,o=r--
  loop:
    - 00_locale
    - resetclock

- name: Remove deprecated configurations
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "~/.startup.d/gpg.sh"
    - "~/.gnupg"
