git:
  advice:
    - detachedHead: false
  alias:
    - lg: log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
    - plog: log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit
    - a: add
    - c: commit
    - d: diff
    - dc: diff --cached
    - st: status
    - sw: switch
  commit:
    - sign: true
    - gpgSign: true
  core:
    - editor: code --wait
  help:
    - autocorrect: 20
  init:
    - defaultBranch: main
  push:
    - default: current
    - autoSetupRemote: true
  user:
    - name: Michael Weigle
    - email: michael.weigle@gmail.com
    - signingkey: CC3E16C90D17E632
