# Java doesn't quite follow the same pattern as other asdf plugins, so it gets
java_version: openjdk
tools:
  - awscli
  - dotnet-core
  - golang
  - gradle
  - maven
  - nodejs
  - packer
  - python
  - ruby
  - terraform
system_packages:
  - jq
  - vagrant
python_packages:
  # mitogen 0.2.x supports ansible < 2.10
  # mitogen 0.3.0 supports ansible = 2.10
  # mitogen 0.3.1 supports ansible < 2.12
  - ansible~=2.10
  - mitogen~=0.3.0
  # ASDF python can't see the python-apt system package, so install it directly
  # pypi is 0.7.8, we need at least 2.1.3+, but main's fairly stable
  - git+https://salsa.debian.org/apt-team/python-apt.git@main
  - awscli
node_packages:
  - mapshaper
  - diff-so-fancy
  - yarn
