# Java doesn't quite follow the same pattern as other asdf plugins, so it gets
java_version: corretto-11
languages:
  - dotnet-core
  - golang
  - gradle
  - maven
  - nodejs
  - packer
  - python
  - ruby
  - terraform
  # - vagrant
system_packages:
  - jq
# Use this until mitogen 0.3.0 is released (master tracks 0.3.0)
python_packages:
  - git+https://github.com/mitogen-hq/mitogen.git@master
  - awscli
node_packages:
  - mapshaper
  - diff-so-fancy
