# Java doesn't quite follow the same pattern as other asdf plugins, so it gets
java_version: corretto-11
tools:
  - awscli
  - dotnet-core
  - golang
  - gradle
  - maven
  - nodejs
  - packer
  - python
  - ruby
  - terraform
  - vagrant
system_packages:
  - jq
python_packages:
  # Use this until mitogen 0.3.0 is released (master tracks 0.3.0)
  - git+https://github.com/mitogen-hq/mitogen.git@master
  # ASDF python can't see the python-apt system package, so install it directly
  # pypi is 0.7.8, we need at least 2.1.3+, but master's fairly stable
  - git+https://salsa.debian.org/apt-team/python-apt.git@master
  - awscli
node_packages:
  - mapshaper
  - diff-so-fancy
