system_packages:
  - jq
python_packages:
  - pip
  - wheel
  # mitogen 0.2.x supports ansible < 2.10
  # mitogen 0.3.0 supports ansible = 2.10
  # mitogen 0.3.1 supports ansible < 2.12
  - ansible~=2.10
  - mitogen~=0.3.0
  # ASDF python can't see the python-apt system package, so install it directly
  # pypi is 0.7.8, we need at least 2.1.3+, but main's fairly stable
  - git+https://salsa.debian.org/apt-team/python-apt.git@main
  - awscli
node_packages:
  - mapshaper
  - diff-so-fancy
  - yarn
  - typescript
  - "@angular/cli"
homebrew_taps:
  - jandedobbeleer/oh-my-posh
homebrew_packages:
  - jandedobbeleer/oh-my-posh/oh-my-posh
