# Java doesn't quite follow the same pattern as other asdf plugins, so it gets
java_version: corretto-11
languages:
  - dotnet-core
  - golang
  - gradle
  - maven
  - nodejs
  - packer
  - python
  - ruby
  - terraform
  - vagrant
system_packages:
  - jq
# Use this until https://github.com/dw/mitogen/pull/739 gets merged
python_packages:
  - git+https://github.com/MetricMike/mitogen.git@master
  - awscli
node_packages:
  - mapshaper
  - diff-so-fancy
