system_packages:
  - podman
  - chrony
python_packages:
  - pip
  - wheel
  # https://github.com/mitogen-hq/mitogen/blob/master/docs/changelog.rst
  # mitogen 0.3.3 supports ansible <= 5
  # mitogen 0.3.4 supports ansible 6 but is not released yet
  - ansible~=5.0
  - mitogen~=0.3.0
  # ASDF python can't see the python-apt system package, so install it directly
  # pypi is 0.7.8, we need at least 2.1.3+, but main's fairly stable
  - git+https://salsa.debian.org/apt-team/python-apt.git@main
  - awscli
node_packages:
  - "@angular/cli"
  - "@prettier/plugin-xml"
  - diff-so-fancy
  - mapshaper
  - typescript
  - yarn
homebrew_taps:
  - jandedobbeleer/oh-my-posh
homebrew_packages:
  - jandedobbeleer/oh-my-posh/oh-my-posh
