system_packages:
  - podman
  - chrony
python_packages:
  - pip
  - wheel
  - ansible~=7.0
  - git+https://salsa.debian.org/apt-team/python-apt.git@main
  - awscli
node_packages:
  - "@angular/cli"
  - "@prettier/plugin-xml"
  - diff-so-fancy
  - mapshaper
  - typescript
  - yarn
homebrew_taps:
  - jandedobbeleer/oh-my-posh
homebrew_packages:
  - jandedobbeleer/oh-my-posh/oh-my-posh
