system_packages:
  - podman
  - chrony
python_packages:
  - pip
  - wheel
  - setuptools
  - ansible~=8.0
  - ansible-lint
  - awscli
node_packages:
  - "@angular/cli"
  - "@prettier/plugin-xml"
  - diff-so-fancy
  - mapshaper
  - typescript
  - yarn
homebrew_taps:
  - jandedobbeleer/oh-my-posh
homebrew_packages:
  - jandedobbeleer/oh-my-posh/oh-my-posh
  - gh
  - gradle-completion
