system_packages:
  - podman
  - chrony
python_packages:
  - pip
  - wheel
  # https://github.com/mitogen-hq/mitogen/blob/master/docs/changelog.rst
  # mitogen support -        0.3.4 : ansible 6 / python 3.10
  #                 - master/0.3.5 : ansible 6 / python 3.11
  #                 -    pull/1017 : ansible 7 / python 3.11
  - ansible~=6.0
  - git+https://github.com/mitogen-hq/mitogen.git@master
  # ASDF python can't see the python-apt system package, so install it directly
  # could steal this from system python, but git's quicker to get updates
  - git+https://salsa.debian.org/apt-team/python-apt.git@main
  - awscli
node_packages:
  - "@angular/cli"
  - "@prettier/plugin-xml"
  - diff-so-fancy
  - mapshaper
  - typescript
  - yarn
homebrew_taps:
  - jandedobbeleer/oh-my-posh
homebrew_packages:
  - jandedobbeleer/oh-my-posh/oh-my-posh
