---
# PowerShell doesn't quite follow the same pattern as other asdf plugins, so they're added separately

- name: Check/Update latest versions of each plugin
  ansible.builtin.include_tasks: asdf_update_plugin.yml
  loop: "{{ tools | dict2items(key_name='name', value_name='version') }}"
  loop_control:
    loop_var: asdf_plugin

- name: Set stable path for JAVA_HOME for other consumers (vscode-java)
  ansible.builtin.shell: /bin/bash -lc "ln -snf $(asdf where java) ~/java_home"

- name: Install/activate latest Powershell
  ansible.builtin.shell: /bin/bash -lc "dotnet tool install --global PowerShell"
  failed_when: false
