---
# PowerShell doesn't quite follow the same pattern as other asdf plugins, so they're added separately

- name: Check/Update latest versions of each plugin
  ansible.builtin.include_tasks: asdf_update_plugin.yml
  loop: "{{ tools | dict2items(key_name='name', value_name='version') }}"
  loop_control:
    loop_var: asdf_plugin

- name: Get ASDF Java directory
  ansible.builtin.command: "asdf where java"
  register: asdf_where_java
  changed_when: false

- name: Set stable path for JAVA_HOME for other consumers (vscode-java)
  ansible.builtin.file:
    src: "{{ asdf_where_java.stdout }}"
    dest: "{{ ansible_user_dir }}/java_home"
    state: link
    force: true

# Not quite sure how to parse this one so Ansible can skip it
- name: Install/activate latest Powershell # noqa: no-changed-when
  ansible.builtin.command: "dotnet tool install --global PowerShell"
