---
- name: Update ASDF
  ansible.builtin.shell: /bin/bash -lc 'asdf update'
# TODO: skip if updated today

- name: Load ASDF plugins
  shell: /bin/bash -lc "asdf plugin-add {{ item }}"
  loop: "{{ tools + [ 'java' , 'rust', 'python' ] }}"
  failed_when: false

- name: Update ASDF plugins
  shell: /bin/bash -lc 'asdf plugin update --all'

- name: "Ensure local bin directory exists"
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.local/bin

- name: Add extra commands
  copy:
    src: "{{ item }}.sh"
    dest: "~/.local/bin/{{ item }}"
    mode: u=rwx,g=r-x,o=r-x
  loop:
    - asdf-prune

- include_tasks: asdf_plugins.yml
