---

- name: Ensure asdf repo is present
  git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: '~/.asdf'

- name: Update ASDF
  shell: /bin/bash -lc 'asdf update'

- name: Load ASDF plugins
  shell: /bin/bash -lc "asdf plugin-add {{ item }}"
  loop: "{{ languages + [ 'java' ] }}"
  failed_when: false

- name: Update ASDF plugins
  shell: /bin/bash -lc 'asdf plugin update --all'

- include_tasks: env.yml
