---
- name: "Ensure completion dir exists"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: u=rwx,g=r-x,o=r-x
  loop:
    - "{{ ansible_user_dir }}/.local/share/bash-completion"

- name: Get ASDF Bash completions
  ansible.builtin.command: "asdf completion bash"
  register: asdf_completion_bash
  changed_when: false

- name: Install asdf completions
  ansible.builtin.copy:
    content: asdf_completion_bash.stdout
    dest: "{{ ansible_user_dir }}/.local/share/bash-completion/asdf.bash"
    mode: u=rwx,g=r--,o=---

- name: Install gradle completions
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/gradle/gradle-completion/master/gradle-completion.bash
    dest: "{{ ansible_user_dir }}/.local/share/bash-completion/gradle-completion.bash"
    mode: u=rw-,g=r--,o=r--
