---

- name: Pretty Log
  git_config:
    name: alias.lg
    scope: global
    value: log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit

- name: Signing
  git_config:
    name: commit.gpgsign
    scope: global
    value: true

- name: Identity
  git_config:
    name: "user.{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  loop:
    - { name: name, value: "Michael Weigle" }
    - { name: email, value: "michael.weigle@gmail.com" }
    - { name: signingkey, value: "CC3E16C90D17E632" }

- name: GH CLI - add apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: C99B11DEB97541F0
    state: present
  become: yes

- name: GH CLI - add repository
  apt_repository:
    repo: deb https://cli.github.com/packages focal main
    state: present

- name: GH CLI - install gh
  apt:
    update_cache: yes
    name: gh
    state: latest
  become: yes
