---
- include_vars: gitconfig.yml

- name: Config
  git_config:
    name: "{{ item.0.key }}.{{ item.1.keys() | list | first }}"
    scope: global
    value: "{{ item.1.values() | list | first }}"
  loop: "{{ git | dict2items | subelements('value') }}"

- name: Signing
  lineinfile:
    create: true
    path: ~/.config/git/allowed_signers
    regexp: "^michael.weigle@gmail.com"
    line: 'michael.weigle@gmail.com namespaces="git" {{ lookup(''url'', ''https://github.com/metricmike.keys'', split_lines=False) }}'

- name: Download autocompletion
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
    dest: ~/.startup.d/10_git-completion.sh
    mode: u=rw-,g=r--,o=r--
