---

# Java doesn't quite follow the same pattern as other asdf plugins, so it's added separately

- name: Install/activate latest versions
  shell: /bin/bash -lc "asdf install {{ item }} $(asdf latest {{ item }}); asdf global {{ item }} $(asdf latest {{ item }})"
  loop: "{{ languages + [ 'java' ] }}"
  when: item != 'vagrant'
  failed_when: false

# Need to get vagrant manually - the generic appimage version for linux doesn't play nice with WSL

- name: Install/activate latest java
  shell: /bin/bash -lc "asdf install java $(asdf latest java {{ java_version }}); asdf global java $(asdf latest java {{ java_version }})"
  failed_when: false

- name: Install/activate latest Powershell
  shell: /bin/bash -lc "dotnet tool install --global PowerShell"
  failed_when: false
