---

# Java and PowerShell don't quite follow the same pattern as other asdf plugins, so they're added separately

- name: Install/activate latest versions
  shell: /bin/bash -lc "asdf install {{ item }} $(asdf latest {{ item }}); asdf global {{ item }} $(asdf latest {{ item }})"
  loop: "{{ tools + [ 'java' ] }}"
  failed_when: false

- name: Install/activate latest java
  shell: /bin/bash -lc "asdf install java $(asdf latest java {{ java_version }}); asdf global java $(asdf latest java {{ java_version }})"
  failed_when: false

- name: Set stable path for JAVA_HOME for other consumers (vscode-java)
  shell: /bin/bash -lc "ln -snf $(asdf where java) ~/java_home"

- name: Install/activate latest Powershell
  shell: /bin/bash -lc "dotnet tool install --global PowerShell"
  failed_when: false

# Remove older asdf versions
# - name: Remove older asdf versions
#   shell: /bin/bash -lc "asdf uninstall {{ item }} where.not $( asdf latest {{ item }});"
#   loop: "{{ tools + [ 'java' ] }}"
#   failed_when: false