---
- name: Update/clean/full-upgrade
  apt:
    update_cache: true
    cache_valid_time: 86400
    autoclean: true
    autoremove: true
    upgrade: full
  become: true

- name: Update system packages
  apt:
    name: "*"
    state: latest
  become: true

- name: Install additional system packages
  apt:
    name: "{{ system_packages }}"
    state: latest
  become: true
  when: system_packages is iterable

- name: Install python packages
  pip:
    name: "{{ python_packages }}"
    state: latest
  when: python_packages is iterable

# List support - https://github.com/ansible-collections/community.general/issues/5421
- name: Install node packages
  npm:
    name: "{{ item }}"
    global: true
    state: latest
  loop: "{{ node_packages | default([]) }}"

- name: Reshim node and python after package installs
  shell: /bin/bash -lc "asdf reshim {{ item }}"
  loop:
    - python
    - nodejs
