---
- include_vars: packages.yml

- name: Update/clean/full-upgrade
  apt:
    update_cache: true
    cache_valid_time: 86400
    autoclean: true
    autoremove: true
    upgrade: full
  become: true

- name: Update system pacakages
  apt:
    name: "*"
    state: latest
  become: true

# - name: Show system packages to install
#   debug:
#     msg: "system_packages: {{ system_packages }}"

- name: Install additional system packages
  apt:
    name: "{{ system_packages }}"
    state: latest
  become: true
  when: system_packages is iterable

# - name: Show python packages to install
#   debug:
#     msg: "python_packages: {{ python_packages }}"

- name: Install python packages
  pip:
    name: "{{ python_packages }}"
    state: latest
  when: python_packages is iterable

# - name: Show node packages to install
#   debug:
#     msg: "node_packages: {{ node_packages }}"

- name: Install node packages
  npm:
    name: "{{ item }}"
    global: true
    state: latest
  loop: "{{ node_packages | default([]) }}"

- name: Reshim node and python after package installs
  shell: /bin/bash -lc "asdf reshim {{ item }}"
  loop:
    - python
    - nodejs

# Update homebrew and upgrade all packages
- homebrew:
    update_homebrew: true
    upgrade_all: true

- homebrew_tap:
    name: "{{ homebrew_taps }}"
    state: present
  when: homebrew_taps is iterable

- homebrew:
    name: "{{ homebrew_packages }}"
    state: latest
  when: homebrew_packages is iterable
