---
- name: Update/clean/full-upgrade
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400
    autoclean: true
    autoremove: true
    purge: true
    upgrade: full
  become: true
  when: ansible_pkg_mgr == "apt"
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Add additional system packages
  ansible.builtin.apt:
    name: "{{ languages_system_packages[ansible_distribution | lower][ansible_distribution_major_version] }}"
    state: present
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

# I'm okay with the potential tradeoff of instability for being on the edge
- name: Update system packages
  ansible.builtin.apt:
    name: "*"
    state: latest # noqa: package-latest
  become: true
  when: ansible_pkg_mgr == "apt"
  vars:
    ansible_python_interpreter: /usr/bin/python3
