---

- name: Update/clean/full-upgrade
  apt:
    update_cache: yes
    cache_valid_time: 86400
    autoclean: yes
    autoremove: yes
    upgrade: full
  become: yes

- name: Add Hashicorp Repo signing key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
  become: yes

- name: Add Hashicorp Repo
  apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ ansible_lsb['codename'] }} main"
  become: yes

- name: Update system pacakages
  apt:
    name: "*"
    state: latest
  become: yes

- name: Show system packages to install
  debug:
    msg: "system_packages: {{ system_packages }}"

- name: Install additional system packages
  apt:
    name: "{{ system_packages }}"
    state: latest
  become: yes

- name: Show python packages to install
  debug:
    msg: "python_packages: {{ python_packages }}"

- name: Install python packages
  pip:
    name: "{{ python_packages }}"
    state: latest

- name: Show node packages to install
  debug:
    msg: "node_packages: {{ node_packages }}"

- name: Install node packages
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
  loop: "{{ node_packages }}"

- name: Reshim node and python after package installs
  shell: /bin/bash -lc "asdf reshim {{ item }}"
  loop:
    - python
    - nodejs
