---

# Ansible & Mitogen don't play well with APT when not using the system python... so don't use the apt module
- name: Update system packages
  ansible.builtin.command: "{{ ansible_user_dir }}/.local/bin/{{ ansible_pkg_mgr }}_updater.sh"

# List support - https://github.com/ansible-collections/community.general/issues/5421
- name: Install node packages
  community.general.npm:
    name: "{{ item }}"
    global: true
    state: latest
  loop: "{{ node_packages | default([]) }}"

- name: Reshim node after package installs
  ansible.builtin.shell: /bin/bash -lc "asdf reshim {{ item }}"
  loop:
    - nodejs
