---
- name: Fetch ohmyposh installer
  ansible.builtin.get_url:
    url: https://ohmyposh.dev/install.sh
    dest: "{{ ansible_user_dir }}/.local/bin/oh-my-posh-install.sh"
    mode: u=rwx,g=r--,o=r--

- name: Run ohmyposh installer
  ansible.builtin.command:
    argv:
      - "{{ ansible_user_dir }}/.local/bin/oh-my-posh-install.sh"
      - -d
      - "{{ ansible_user_dir }}/.local/bin"
