---
- name: Enable linger
  ansible.builtin.command: "loginctl enable-linger metricmike"
  become: true

- name: Pick up new systemd units
  ansible.builtin.systemd_service:
    scope: user
    daemon_reload: true

- name: Start services
  ansible.builtin.systemd_service:
    scope: user
    state: started
    name: "{{ item }}"
  loop:
    - ollama
    - ara-server
