---
- name: Silence login motd
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.hushlogin"
    state: touch

# https://github.com/arkane-systems/genie/wiki/Systemd-units-known-to-be-problematic-under-WSL#systemd-remount-fsservice
- name: Remove problematic cloudimg-rootfs
  mount:
    path: /
    src: LABEL=cloudimg-rootfs
    state: absent_from_fstab
  become: true
