python_packages:
  - pip
  - wheel
  - setuptools
  - ansible
  - ansible-lint
  - awscli
node_packages:
  - "@angular/cli"
  - "@prettier/plugin-xml"
  - diff-so-fancy
  - mapshaper
  - typescript
  - yarn
